version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/uniq
    #overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu